config {
  type: "table",
  name: "stg_paint"
}

SELECT
  percentage_newly_painted_homes_per_year,
  percentage_repainted_homes_per_year,
  colored_paint_market_share,
  paint_bll_impact_ug_per_dl,
  health_dalys_per_bll,
  iq_points_lost_per_bll,
  number_of_years_spent_working,
  income_loss_percentage_per_iq_point,
  daly_to_income_factor,
  health_dalys_discount_rate,
  income_dalys_discount_rate,
  program_success_probability,
  percentage_urban_homes_painted,
  percentage_rural_homes_painted
FROM
  ${ref("paint")}