config {
  type: "operations",
  tags: ["sources"],
  disabled: true
}

CREATE OR REPLACE EXTERNAL TABLE `leep-data-system.paint.counterfactual`
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1xMp67BHAGJWqwOIQslr_V7yuLvlpEl9ISGY9zbDo_Qw/edit'],
  skip_leading_rows = 1
);

CREATE OR REPLACE EXTERNAL TABLE `leep-data-system.paint.assumptions`
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1vNDJpcBFYQEPbQSHo3813me2KgC_v_S3XZteI5hQDYY/edit'],
  skip_leading_rows = 1
);

CREATE OR REPLACE EXTERNAL TABLE `leep-data-system.paint.industry_full_raw`
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/15_iXYG59jYJk6Psg9fSBgRlzX8dx1EucPQI78Pnjqh4/edit'],
  sheet_range = 'All Tracker Data',
  skip_leading_rows = 1
);

CREATE OR REPLACE EXTERNAL TABLE `leep-data-system.core.discount_rates`
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1Yb910LqJIYw00n3gev_otvR6Td88czZ3ZWpGhHOmeM4/edit'],
  skip_leading_rows = 1
);